### ISSUE TITLE
Feature Request: Unknown Word Replacement

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#105]
It would be nice to have options for unknown word replacement, either with the original word or using a lexicon.

**Comment by pmichel31415** [comment]
I'm interested in helping for this, how would I go about doing it?

**Comment by neubig** [comment]
We probably need to:
1. save the original Input object somewhere, maybe as additional information in the ExpressionSequence, or maybe just separately?
2. in the Inference object, we need to allow it to take in this Input, and the attention weights, then if the output is an "unk" instead use the plain-text string from the Input.

There might be a more elegant way as well? This would also be very nice, as it would allow us to more easily implement the copy mechanism as well:
https://github.com/neulab/xnmt/issues/221

**Comment by msperber** [comment]
I'm not sure which is the most elegant, but the ```on_start_sent``` handler also propagates the input sentence so maybe the inference object can just capture it this way.

**Comment by neubig** [comment]
Yeah, that sounds like a good idea.
