### ISSUE TITLE
Feature Request: Tokenization

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#107]
It would be nice to be able to perform tokenization/detokenization as part of the preprocessing capability: https://github.com/neulab/xnmt/pull/104

Options include BPE, sentencepiece, or manual tokenization like the Moses tokenizer. For ease of implementation, particularly for sentencepiece, I think it's OK to assume a call to an external program when implementing these.

**Comment by john-hewitt** [comment]
Is this still open? I'd be interested in pitching in if it's not on someone's local branch somewhere.

**Comment by neubig** [comment]
Yep, this is still open. Go for it, thanks!

**Comment by DevSinghSachan** [comment]
Hi John, 
I wrote some code to work with sentencepiece library which you may find helpful. It calls 'sentencepiece' in line 64 with various options.
https://github.com/neulab/xnmt/pull/64/files#diff-d92e2671b19cf58472181ab90e3cc45c

**Comment by john-hewitt** [comment]
Thanks for the pointer.!

I'm adding a work-in-progress MR with some stubs and docs. It's not ready for merging; just here for comments and suggestions as I keep working.

**Comment by john-hewitt** [comment]
Quick question here. When running multiple tokenizers, let's say we have the following portion of a config file:

    - type: tokenize
      in_files:
      - examples/data/train.ja
      - examples/data/train.en
      - examples/data/dev.ja
      - examples/data/dev.en
      - examples/data/test.ja
      - examples/data/test.en
      out_files:
      - examples/data/train.tok.ja
      - examples/data/train.tok.en
      - examples/data/dev.tok.ja
      - examples/data/dev.tok.en
      - examples/data/test.tok.ja
      - examples/data/test.tok.en

To apply multiple tokenizers to the same input file, I expect there would be a second `- type: tokenize`, as the multiple `spec`s seem to only be able to apply different tokenizers to different files -- not to the same file. Is this correct?

**Comment by neubig** [comment]
I think perhaps it would be good to give both options. Sometimes you might want to save the intermediate files sometimes not. Why don't you come up with an initial prototype that fits your needs, and if we need to expand it later then we can do so. Thanks!

**Comment by neubig** [comment]
This has been fixed.
