### ISSUE TITLE
Decoder is not initialized to final encoder state

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#132]
It is important to initialize the decoder with the final state of the encoder, but we are not doing this well. We should fix this:
https://github.com/neulab/xnmt/blob/master/xnmt/translator.py#L91

**Comment by philip30** [comment]
#168

**Comment by philip30** [comment]
This issue should be done right now right, @neubig ?

**Comment by neubig** [comment]
Yep, thanks!
