### ISSUE TITLE
Feature Request: "Attention is All You Need"

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#133]
This is a very interesting paper which shouldn't be super-difficult to implement, and would also test the extensibility of xnmt: https://arxiv.org/abs/1706.03762

If someone is interested I think this would be a great example to have.

**Comment by DevSinghSachan** [comment]
I would be interested in taking up this and have it as an example.

**Comment by neubig** [comment]
Great, go for it!

**Comment by neubig** [comment]
Done by @DevSinghSachan !
