### ISSUE TITLE
Travis CI is failing

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#169]
Travis CI checks are failing on the pip install of DyNet. I'm guessing that this is something simple like not installing mercurial or the compile environment beforehand, and might be resolved by adding packages to the `.travis.yml` file: http://dynet.readthedocs.io/en/latest/python.html

@philip30 if you have time today perhaps you could take a look? If not, I'll try to take a look later.

**Comment by philip30** [comment]
@neubig  I will try to take a look at it!

**Comment by philip30** [comment]
@neubig It seems that the pip install was OK. But dynet python can not be found.

https://travis-ci.org/neulab/xnmt/jobs/265638184#L508

I inspect the build normally when using setup.py. It seems that the automatic build will skip the python building if there is no "build" directory inside dynet.

**Comment by neubig** [comment]
@philip30 I fixed a lot of the problems with Travis. It seems that there are a few still breaking, both involved with segmenting encoder in some way. One is because the enum package can't be installed on Python 3, and another is just because a test is failing. Could you take a look? It might be nice to remove the dependency on the enum package if it's not critical.

**Comment by MattX** [comment]
I think the reason it fails is that in Python 3, enum was moved to the standard library.

It should be possible to replace the `enum` line in requirements.txt by `enum; python_version < '3'` to make it a requirement only on Python 2. According to [this Stackoverflow answer](https://stackoverflow.com/a/33451105/), it would require some changes to `setup.py` as well, though.

**Comment by neubig** [comment]
Fixed by https://github.com/neulab/xnmt/pull/198

**Comment by MattX** [comment]
[Looks like it's failing again](https://travis-ci.org/neulab/xnmt/builds/286335065) on `test_translator_loss`. The logs show the seed was correctly set to 2, but we might want to also set the numpy and python seeds since there are quite a few calls to `random` and `np.random`.
