### ISSUE TITLE
Cython setup doesn't work on Mac OS?

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#199]
It seems that cython is broken on mac OS, e.g.:

    (python3) neubig@itachi:~/work/xnmt$ python setup.py build_ext --inplace --use-cython-extensions
    running build_ext
    building 'xnmt.cython.xnmt_cython' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/neubig/anaconda/envs/python3/include -arch x86_64 -I/Users/neubig/anaconda/envs/python3/include -arch x86_64 -I/Users/neubig/anaconda/envs/python3/include/python3.6m -c xnmt/cython/xnmt_cython.cpp -o build/temp.macosx-10.7-x86_64-3.6/xnmt/cython/xnmt_cython.o -std=c++11
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/neubig/anaconda/envs/python3/include -arch x86_64 -I/Users/neubig/anaconda/envs/python3/include -arch x86_64 -I/Users/neubig/anaconda/envs/python3/include/python3.6m -c xnmt/cython/src/functions.cpp -o build/temp.macosx-10.7-x86_64-3.6/xnmt/cython/src/functions.o -std=c++11
    xnmt/cython/src/functions.cpp:3:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1

**Comment by philip30** [comment]
Hmm, I am also working with mac, but the problem does not occur.
I see some fix in https://stackoverflow.com/questions/40301619/unordered-map-file-not-found-error-when-compiling-with-xcode-7-3-1

if you modify setup.py and add
"-stdlib=libc++" in extra_compile_args, will that work in your environment?

**Comment by neubig** [comment]
Thanks! I ended up needing to do something platform neutral that was a bit more complicated, but that was helpful.
