### ISSUE TITLE
WordTrgSrcBatcher is not working in the current master branch.

### ISSUE THREAD

**Issue by philip30** [neulab/xnmt#232]
After merging master branch to my current working branch I found that there is a bug in the current implementation of WordTrgSrcBatcher. It is just broken and does not work. Has it been tested yet btw?

**Comment by msperber** [comment]
I haven't used it and we only have unit tests for SrcBatcher and WordSrcBatcher so far, so I think it would be useful to add tests for the other batchers as well.
