### ISSUE TITLE
preproc.yaml should include SentencePiece detokenization

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#234]
I believe this is missing detokenization when evaluating BLEU score: https://github.com/neulab/xnmt/blob/master/examples/preproc.yaml

**Comment by john-hewitt** [comment]
A grep showed that `detokenize` is never called anywhere in the pipeline, though preproc.py is set to be able to call the SentencePiece tokenizer. So, it's likely more than just a config file problem. Would such a call go somewhere like [here](https://github.com/neulab/xnmt/blob/c6fac72d109de8b7dffa2c6b15514ff4589565ef/xnmt/xnmt_decode.py#L118), in the decoder output processor? Or in `xnmt_evaluate.py`?

**Comment by neubig** [comment]
Yes, I think that function is what you want, and it probably just needs to be added to the config file. Thanks!

**Comment by neubig** [comment]
Fixed by #248
