### ISSUE TITLE
dynet-seed doesn't work?

### ISSUE THREAD

**Issue by philip30** [neulab/xnmt#265]
Currently, the dynet-seed option does not seem to work. Every time we initialize the model, even with given seed, it always initializes the parameter differently. This means this option is currently useless.

I take a look at the code and do a little debugging. Step: adding printing the value of the self.W1 in xnmt/linear.py::Linear::__init__ right after it is added to the model, it always print different value? I think this should be fixed upstream in dynet. I saw that it is using XavierInitialization by default in dynet/model.cc and I trace it until it uses this piece of code:

``` C++
// dynet/tensor.cc line 269
void TensorTools::randomize_uniform(Tensor& val, real left, real right) {
  uniform_real_distribution<real> distribution(left, right);
  auto b = [&] {return distribution(*rndeng);};
  if (val.device->type == DeviceType::CPU) {
    generate(val.v, val.v + val.d.size(), b);
#if HAVE_CUDA
  } else if (val.device->type == DeviceType::GPU) {
    float* t = new float[val.d.size()];
    generate(t, t + val.d.size(), b);
    CUDA_CHECK(cudaSetDevice(((Device_GPU*)val.device)->cuda_device_id));
    CUDA_CHECK(cudaMemcpy(val.v, t, sizeof(real) * val.d.size(), cudaMemcpyHostToDevice));
    delete[] t;
#endif
  } else { throw std::runtime_error("Bad device type"); }
}
```

I don't see the seed is being used here? (or maybe somewhere invisible to me) I think it should if we want to make the seed somewhat useful. Anyway, the problem still exists in XNMT even if there is nothing wrong with DyNet.

**Comment by neubig** [comment]
What is your exact command line? Are the DyNet-related command line options specified before any other options? My guess is that you have a different option before the DyNet-related options, which is not allowed by DyNet. See the documentation here:

http://dynet.readthedocs.io/en/latest/commandline.html

If not, this is a bug in DyNet and should be fixed.

**Comment by philip30** [comment]
What I did was I change the dynet seed value in the xnmt_run_experiments to be some fixed value (by adding default) and let the test run. I try to print the weight at the specific test, and it always produces different values. Is this enough to check? I will do the debugging more when I get back to Pittsburgh.

**Comment by neubig** [comment]
If you give me the exact command line that you ran I can help.

But I actually thought of another thing that you can check. At the beginning, DyNet reports its random seed value:

    >>> import dynet
    [dynet] random seed: 3443915496
    [dynet] allocating memory: 512MB
    [dynet] memory allocation done.

If this reported random seed value is set to what you expect, but the parameters are still being initialized incorrectly, then this is a bug in DyNet. If the reported random seed value is not set to what you expect, for some reason you are not passing the argument in to DyNet correctly. This is probably a result of not putting DyNet arguments before other arguments on the command line.

**Comment by philip30** [comment]
I confirmed that this is no longer the case. Sorry!
