### ISSUE TITLE
XNMT parameter saving / loading

### ISSUE THREAD

**Issue by philip30** [neulab/xnmt#280]
I saw it with bare eyes that mod.data contain the weight of the parameters in a string float format. I think this makes some of the bytes got canceled because it is not possible to store floats in a string format. 

Moreover, I think it will be faster if we save/load the values of the weights using bytes, so we don't have to parse it. Or am I missing something?

**Comment by neubig** [comment]
This is definitely something that would be nice to have, but it's actually an issue with DyNet, not xnmt: https://github.com/clab/dynet/issues/648

If you're willing to help with this we'd certainly welcome a PR!
