### ISSUE TITLE
Sentencepiece integration

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#321]
Not sure if that'll be helpful but FWIW sentencepiece now has official python bindings (https://github.com/google/sentencepiece/blob/master/python/README.md), which might be more convenient for several reasons:

- can be installed with pip (no separate installation, just add to `requirements.txt`
- easier on-the-fly tokenization/detokenization

**Comment by neubig** [comment]
Awesome! We should definitely use this, assuming it supports training.

**Comment by pmichel31415** [comment]
It does! I've been using it for another project. Here's what the API looks like:

Training:
```python
import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=/path/to/corpus/file --model_prefix=my.model.name --model_type=bpe --vocab_size=8000')
```
Tokenizing
```python
import sentencepiece as spm
sp = spm.SentencePieceProcessor()
sp.Load('my.model.name.model')
sp.EncodeAsPieces('a sentence') # ['a', '_sent', 'ence']
```

**Comment by pmichel31415** [comment]
OK this is basically done now
