### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#325]
Seems like readthedocs is not generating the documentation properly:
http://xnmt.readthedocs.io/en/latest/api_doc.html#bridge
Here's what I see (on firefox):
![image](https://user-images.githubusercontent.com/10391785/38696587-9bed66a8-3e5d-11e8-9966-8dd9ad548c0b.png)

**Comment by pmichel31415** [comment]
After looking at the logs I suspect this is caused by the type annotations which are not taken into account by `doc/source/doc_utils.py`

**Comment by msperber** [comment]
Thanks for the hint! I added ```sphinx_autodoc_typehints``` but the build is still failing. What would need to be done about multiline arguments?

**Comment by neubig** [comment]
If I remember correctly, we might have been doing the difficult stuff related to cleansing the source files because it was difficult to install DyNet on the readthedocs server. Now that it's easy to install DyNet via pip, maybe things will work by just doing that?

**Comment by pmichel31415** [comment]
Yes basically @neubig is right. Sphinx requires the module to be installed on the system. Right now xnmt is using a script I wrote for dynet that creates a "dummy" module by removing everything but the function/classes signatures and docstrings. The resulting module is used to grenrate the documentation.

Presently this script fails on multiple line arguments/type annotations and overall isn't very stable. If there's an easy way to install xnmt on a relatively constrained environment (the readthedocs servers), eg pip install, this would be a better solution.

**Comment by neubig** [comment]
Should be fixed by https://github.com/neulab/xnmt/pull/334 !
Thanks @msperber , this was long overdue :)

**Comment by pmichel31415** [comment]
Wow good work @msperber , looks like it works again. I'll close this issue then
