### ISSUE TITLE
Better Versioning of XNMT

### ISSUE THREAD

**Issue by philip30** [neulab/xnmt#336]
Currently I am experiencing several versioning issues on XNMT. Within the same branch (master) I can have my model obsolete (not being able to be loaded) by different versions of code. This thing happens when we change the structure of the constructor so the persistence does not work anymore. 
For example, I changed the constructor in SimpleInference in my recent commits:

- Before 
```
inference: !SimpleInference
  len_norm_type: !PolynomialNormalization
     apply_during_search: True
  beam: 5
```

- After
```
inference: !SimpleInference
  search_strategy: !BeamSearch
    len_norm: !PolynomialNormalization
      apply_during_search: True
    beam_size: 5
```

As we can see the serialization will not work in this case, because there is no way to infer the after from the before. I want to open a discussion about fixing this thing. With the increasing number of people using XNMT, I think it is best to solve this problem. Here are things to consider:
1. Make a script to upgrade the xnmt model. Here we can define a rule to modify the mod file directly (which I usually do by hand) of a previous version of the model into the current one. The script will be like applying patches that should be written every time a significant refactoring occurs. This solution needs us to track the version of the model.
2. Let us make a released version of XNMT (master) and separate the current activity of master branch into development branch. The master branch should be on the latest release. It is easier to go back between release than going back between commits I think.
3. Maybe we should define rule not to delete any arguments on ``__init__ ``? We can mark the parameter as obsolete and said it is not used anymore. But if the parameters contains some parameters inside it, this can be a problem.

**Comment by msperber** [comment]
I have experienced those problems also. I personally feel we're still far from converging to a stable interface and shouldn't try to freeze anything. But using release tags and communicating that releases may not be backward compatible seems like a good idea to me. Upgrading via scripts seems useful but might be a lot of effort to write and/or maintain? I've used [Django SQL data base migrations](https://docs.djangoproject.com/en/2.0/topics/migrations/) before which is a related idea but quite complicated.

**Comment by neubig** [comment]
Re: the original comment by @philip30 

1. This might be useful. What about a script that takes your experiment config file before and after, and applies the same thing to the model file?
2. No, I like master to be the development version. It makes things easier. I think we could have versioning though. Like every time before @msperber refactors the entire serializer :)
3. I'm a little bit ambivalent about this one.

Let me add one additional thing:

4. What about printing out the git commit ID every time we run xnmt? This would allow us to at least know which version we used to train the model, so we could revert to this for testing if necessary.

**Comment by msperber** [comment]
Number 4 is already kind of happening here: https://github.com/neulab/xnmt/blob/master/xnmt/xnmt_run_experiments.py#L78

It only appears under "debug" verbosity and is currently not written into log files because the file stream is set up after this log happens, but that could be fixed.

**Comment by mbollmann** [comment]
FWIW, I also think release tags are the way to go. They don't really necessitate a separate development branch, and at the same time make it easy to specify which version of the library works with a given configuration file, for example.

**Comment by neubig** [comment]
Started versioning here: https://github.com/neulab/xnmt/releases/tag/0.1.0

Will close.
