### ISSUE TITLE
Sharing vocabulary between source and target?

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#339]
Is there a way to share vocabulary between source and target language? Didn't find anything i the documentation

**Comment by neubig** [comment]
This should be easy through component sharing? https://github.com/neulab/xnmt/blob/master/examples/11_component_sharing.yaml

Just define the target vocabulary as a reference to the source vocabulary. If this doesn't work or you think extra documentation is necessary we can fix.

**Comment by pmichel31415** [comment]
I see. Maybe this should be mentioned somewhere in the docs beyond the example config file?
