### ISSUE TITLE
A bunch of questions/remarks from a newbie

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#343]
Hi, here's a list of questions I have. None of them warrant a separate issue, but clarifying those would help new users such as myself

- [x] How do I force the overwrite of the log file? The error message isn't very clear `please delete by hand if you want to overwrite it (or use --settings debug or otherwise set OVERWRITE_LOG=True)` (what is the `OVERWRITE_LOG` variable and where can I change it?)
- [ ] The documentation on the translator structure (http://xnmt.readthedocs.io/en/latest/translator_structure.html) is a bit terse. For instance I had trouble figuring out what an `MlpSoftmaxDecoder` was. Something that would help is to describe a common baseline model (with equations/diagrams and everything) and then show a config file *where all the parameters are specified* that reproduces it
- [x] Errors in the doc/examples (I think): 
  - in http://xnmt.readthedocs.io/en/latest/experiment_config_files.html#model adding a `layers` argument to the `MlpSoftmaxDecoder` doesn't work for me
  - https://github.com/neulab/xnmt/blob/master/recipes/stanford-iwslt/config.en-vi.yaml#L20-L21 passing a `beam` argument to `SimpleInference` raises an error `ValueError: 'beam' is not a accepted argument of SimpleInference.__init__(). Valid are ['src_file', 'trg_file', 'ref_file', 'max_src_len', 'post_process', 'report_path', 'report_type', 'search_strategy', 'mode', 'max_len', 'batcher']`
  - The docstring for this class http://xnmt.readthedocs.io/en/latest/api_doc.html#xnmt.length_normalization.LengthNormalization seems to be wrong 
  - probably others I didn't find. IMO the outdated API in the examples is a bigger problem than wrong docstrings
- [x] In the API reference it would be nice if the base class were located before the inherited classes (not sure if there's a way to enforce this with sphinx) 
- [x] Can I overwrite `EXP_DIR` in the config file to point to a directory of my choice?
- [x] How do I set the random seed for everything (for reproducibility)

I will update if I run into more issues.

PS: I'm using the latest master

**Comment by msperber** [comment]
Thanks for finding these!
re 1: as of #345, this is documented under xnmt/settings.py
re 3: thanks for catching these; fixed as of #345 
re 4: also not sure, but I did add ```show-inheritance``` flags so we can at least follow the link to the base class
re 5: I hadn't thought about this, but turns out you can: simply overwrite EXP_DIR in the experiment.exp_global.placeholders dictionary. Or, adjust it in xnmt.settings to change locations for all experiments you run.
re 6: --dynet-seed changes seeds for both dynet and XNMT.

**Comment by pmichel31415** [comment]
Thanks for the quick response @msperber 
I'll still leave this open for the translator structure documentation part

**Comment by neubig** [comment]
I think the documentation has been improved significantly, so maybe we can close this?
