### ISSUE TITLE
Controlling order of preprocessing operations

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#350]
Is there a way to control the order in which preprocessing operations are executed? In my case I'm using sentencepiece for tokenization and I need to lowercase the data before learning the tokenization model.

However, putting the !PreprocNormalizer ahead of the !PreprocTokenizer in the yaml file didn't help (xnmt tried to tokenize first and failed because it couldn't find the lowercased files).

I ended up lowercasing "by hand" outside of xnmt.

**Comment by neubig** [comment]
Strange, it used to be that you could specify in order. Maybe this has changed?

**Comment by pmichel31415** [comment]
OK I must have messed up somewhere because it works fine now. I'll close this issue
