### ISSUE TITLE
Implementing character based embeddings

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#392]
I'm trying to reproduce a model from [Synthetic and Natural Noise Both Break Neural Machine Translation](https://arxiv.org/abs/1711.02173) where the word embeddings are the average of the character embeddings.

How would I go about implementing that in xnmt?

To be clear I don't want a character based model, I want a model that processes the input as a sequence of words, but instead of having one embedding per word, has one embedding per character and represents each word as the average of its characters.

**Comment by neubig** [comment]
Probably you need to create a version of the input class that doesn't
convert words to integer IDs, but instead saves their strings. Then it
would be as simple as implementing a new version of the word embedder that
reads in the characters and does lookup and sum appropriately.

Graham

-- Sent from my phone so apologies for brevity and typos.

**Comment by neubig** [comment]
Just remembered that @philip30 already has something like this in his segmenting transducer branch. He might be able to give pointers.

**Comment by philip30** [comment]
Yes, I have that exactly as it is said.
I am also using that in my experiment.
It can be seen in this unittest:

https://github.com/neulab/xnmt/blob/segmentation_experiment/test/test_segmenting.py#L173

Though, I don't have the example of the YAML config, but the correct class can be constructed appropriately by looking at the unittest. It is not yet merged, however :( I will resolve the #380 when I have time to do so!

**Comment by neubig** [comment]
Should be fixed by #380.
