### ISSUE TITLE
A few problems regarding masking

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#419]
- [ ] Mask dimensions don't match the DyNet canonical order

It seems that the batch dimension is first, which is the opposite of what DyNet expects:

https://github.com/neulab/xnmt/blame/master/xnmt/batcher.py#L40

- [x] Comment is stale

https://github.com/neulab/xnmt/blob/master/xnmt/expression_sequence.py#L16

says it should be a "numpy array" but instead, it's actually a mask object

**Comment by msperber** [comment]
The second problem has been fixed. Before addressing the first one, it might be good to think about how masks would look like with a swappable backend because PyTorch indexes things the opposite way from DyNet.
