### ISSUE TITLE
Type safety for SeqTransducers, defined Unidirectional transducers

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#437]
I was looking at refactoring the residual encoders, as they were proving useful and I wanted to test them in the decoder, but I realized that the interface to SeqTransducer in general could use a bit of reworking. I think this can wait until https://github.com/neulab/xnmt/pull/429 is done, but it'd be nice to have type safety for the transducers to ensure that their interface is implemented cleanly.

Also, I'd like to have support for unidirectional transducers, basically things that support the "add_input" function.

**Comment by msperber** [comment]
One thing I've also noticed is that there is currently no clean way to use ```add_input()``` with masks. This isn't needed in the standard decoder, but would be useful for some types of models.

**Comment by neubig** [comment]
Will be fixed by https://github.com/neulab/xnmt/pull/429
