### ISSUE TITLE
References cannot be used as shared parameters

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#441]
In this line of code, the serializer skips parameter sharing if the shared parameter is a reference:

https://github.com/neulab/xnmt/blob/master/xnmt/persistence.py#L1152

This seems like an unnecessary restriction to me, and is making things a bit more complicated when refactoring. Is there a reason for this? @msperber

**Comment by msperber** [comment]
Honestly, I don't quite remember what the reason for this was. Maybe there are some tricky corner cases... how were you thinking of using this?

**Comment by neubig** [comment]
For example, here:
> https://github.com/neulab/xnmt/pull/440/files#diff-a93a58304a6429d00e78547362266ba7L25

There are shared parameters between `model.rnn.encoder` and `model.transform.aux_input_dim`, but `model.rnn.encoder` is specified as a reference to `exp_global.default_layer_dim` and `model.transform.aux_input_dim` is not defined. Because the reference doesn't get recognized, it has to be specified explictly. I don't want to set the default of `model.transform.aux_input_dim` as a reference to `exp_global.default_layer_dim`, because it make more sense to have it as 0 most of the time.

**Comment by msperber** [comment]
Ok I see. Would it be an option to add an AuxNonLinear class that subclasses NonLinear but adds an aux argument including default value? I had added OutputMLP and AttentionalOutputMLP for similar reasons.
Changing the persistence code is always a bit tedious, but otherwise I could also look into supporting the use case.

**Comment by neubig** [comment]
OK, I'll do that for now. But I think perhaps we should leave this issue open. It seems that the behavior of following references for shared parameters would be more desirable. Thanks!
