### ISSUE TITLE
Documentation on partial population hard to find

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#443]
I got the following error, but I'm not sure what documentation I should see to resolve the problem. Maybe a link would be warranted?

    > populated a subset of DyNet weights from given data files: ['UniLSTMSeqTransducer.f9721482', 'UniLSTMSeqTransducer.13054fdf', 'UniLSTMSeqTransducer.db1098a3', 'UniLSTMSeqTransducer.9fec3d70', 'UniLSTMSeqTransducer.61453456', 'UniLSTMSeqTransducer.d98c0fa2', 'UniLSTMSeqTransducer.64c07b00', 'UniLSTMSeqTransducer.fb34328c'].
      Did not populate {'Softmax.796c1d8a', 'UniLSTMSeqTransducer.eb62fc5c', 'AutoRegressiveDecoder.16c8b2e1', 'SimpleWordEmbedder.ce82907c', 'AuxNonLinear.468b164b', 'MlpAttender.6bdd861b', 'Linear.88ec310e', 'SimpleWordEmbedder.3f2bdbb6'}.
      (Note: if partial population was not intended, likely the unpopulated component or its owner   does not adhere to the Serializable protocol correctly, see documentation).

**Comment by neubig** [comment]
@msperber

**Comment by msperber** [comment]
This should refer here: http://xnmt.readthedocs.io/en/latest/writing_xnmt_classes.html#using-serializable-subcomponents

**Comment by neubig** [comment]
Will be fixed by https://github.com/neulab/xnmt/pull/440
