### ISSUE TITLE
Potential model base interface issue

### ISSUE THREAD

**Issue by msperber** [neulab/xnmt#507]
https://github.com/neulab/xnmt/blob/e06711ba0c666a828fd4c38ca7f0ac186c7863d8/xnmt/models/base.py#L67

Does this and other interface definitions of calc_nll need to be updated? It seems the return type is now a DyNet expression and loss_calculator is no longer passed.

**Comment by neubig** [comment]
Yes. I think @philip30 probably fixed the name but not the profile.
