### ISSUE TITLE
"how do I?" section of the doc

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#522]
It'd be nice to have a "how do I?" section of the doc that would let people easily find the examples that make it possible to do various things.

**Comment by msperber** [comment]
The example config folder has gotten a bit big, some parts are also redundant with test configs, others even outdated. Shall we begin by only keeping some xnmt core features there (probably 10 or 15 example configs), and moving the rest as prose or config snippets into this new section, while making sure that everything is also captured by unit tests? We could also refer to some test configs from the "how do I" section.
