### ISSUE TITLE
Significant number of "unks" even when using subword units

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#524]
I've noticed in several of my experiments that xnmt is generating "<unk>s" even when using sentencepiece, which is strange. This issue is a reminder to myself to check why this is happening and see if it's a bug in xnmt itself, or just in my experimental setup.

**Comment by philip30** [comment]
This actually does not happen to me.

I use sentpiece but I didn't use the xnmt preprocessing script to prepare the data.
