### ISSUE TITLE
Search Strategies assume decoder supports calc_log_probs

### ISSUE THREAD

**Issue by armatthews** [neulab/xnmt#561]
Right now all search strategies rely on the decoder being able to provide (log) probabilities over the whole vocabulary. For some setups this might be woefully inefficient (e.g. class-factored softmaxes), and for others it might be downright impossible (e.g. my open-vocabulary morphology [work](http://www.aclweb.org/anthology/N18-1130)).

I propose we refactor things so that decoders implement operators ``top_k`` and/or ``sample``. These functions should return (word, score) pairs. I believe this change would maintain the functionality of all existing decoders and search strategies, while allowing for a much broader class of decoders to be implemented.

Thoughts?

**Comment by neubig** [comment]
I think the concept like this is already implemented in the Scorer class
somewhat. Probably the decoders would need to be modified to use the
functions implemented in Scorer appropriately.

**Comment by neubig** [comment]
Sorry, not the Decoder class, but whether the SearchStrategy class.
