### ISSUE TITLE
dy.sigmoid doesn't exist

### ISSUE THREAD

**Issue by justinvdh** [neulab/xnmt#576]
https://github.com/neulab/xnmt/blob/master/xnmt/modelparts/transforms.py

Xnmt calls dy.sigmoid, but Dynet uses a different name for the sigmoid function. 

Dynet currently has dy.logistic and dy.log_sigmoid, although I'm not quite sure what the difference between those two is.

**Comment by philip30** [comment]
hi Justin,

I think this is an XNMT bug. The correct code should be ```dy.logistic```
