### ISSUE TITLE
Experiment Configuration File Format

### ISSUE THREAD

**Issue by gmwe** [neulab/xnmt#88]
The documentation _Experiment Configuration File Format_ seems to be outdated. 
For example: **train_target** vs **train_trg**.

**Comment by roeeaharoni** [comment]
also **eval_every** (in current documentation) vs. **decode_every** (in xnmt_run_experiments.py).

**Comment by roeeaharoni** [comment]
created a pull request in #89

**Comment by neubig** [comment]
Should be fixed by #89
